In [1]:
import numpy as np

In [2]:
def leaky_relu(x):
  return x if x > 0 else .01 * x

def leaky_relu_derivative(x):
  return 1 if x > 0 else .01

In [4]:
def activation(input_array):
  input_activations = np.zeros((input_array.shape[0] + 1, ))
  input_activations_gradients = np.zeros((input_array.shape[0] + 1, ))
  for i in range(input_array.shape[0]):
    input_activations[i] = leaky_relu(input_array[i])
    input_activations_gradients[i] = leaky_relu_derivative(input_array[i])
  input_activations[input_array.shape[0]] = 1.0
  return input_activations, input_activations_gradients

In [9]:
class NeuralNetwork:

  def __init__(self, number_of_layers, number_of_neurons_per_layer):
    self.size = number_of_layers
    self.network = np.empty((number_of_layers, ), dtype=np.ndarray)
    self.gradients = np.empty((number_of_layers, ), dtype=np.ndarray)

    for i in range(self.size):
      #self.network[i] = np.full((self.size, self.size + 1), 1.0)
      self.network[i] = np.random.uniform(-.3, .3, (number_of_neurons_per_layer, number_of_neurons_per_layer + 1))
      self.gradients[i] = np.zeros((self.size, self.size + 1))

    self.activation_gradients = np.zeros((self.size, self.size + 1))
    self.layer_gradients = np.zeros((self.size + 1, self.size))
    self.mults = np.zeros((self.size, self.size + 1))


  def feed_forward(self, x_inputs):
    previous_activations = np.append(x_inputs, 1.0)
    previous_temp = np.array([])
    for i in range(self.size):
      self.mults[i] = previous_activations
      temp = np.dot(self.network[i], previous_activations)
      previous_activations, self.activation_gradients[i] = activation(temp)
      if (i-1 >= 0):
        self.layer_gradients[i - 1] = previous_temp
      previous_temp = temp
    self.layer_gradients[self.layer_gradients.shape[0]-2] = temp
    return previous_activations[:previous_activations.shape[0]-1]

  def gradient_descent(self, dE_dOutput):
    output_layer_gradient = np.full((self.layer_gradients.shape[1], ), dE_dOutput)
    self.layer_gradients[self.layer_gradients.shape[0]-1] = output_layer_gradient
    self.layer_gradients = np.flip(np.multiply.accumulate(np.flip(self.layer_gradients)))


  def __repr__(self):
    s = ""
    for i in range(self.network.shape[0]):
      s += f"Layer: {i+1} \n{str(self.network[i])}\n\n"
    return s

In [13]:
nn = NeuralNetwork(2, 2)
print(nn)

Layer: 1 
[[-0.02078135  0.25013627  0.12129649]
 [-0.11203934  0.22134885 -0.29520984]]

Layer: 2 
[[-0.00657517  0.29305864  0.00038872]
 [ 0.01714371  0.27777136 -0.13187026]]




In [10]:
a = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0], [4.0, 4.0, 4.0]])
print(a)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [11]:
b = np.multiply.accumulate(np.flip(a))
print(np.flip(a), '\n')
print(b, "\n")

[[4. 4. 4.]
 [3. 3. 3.]
 [2. 2. 2.]
 [1. 1. 1.]] 

[[ 4.  4.  4.]
 [12. 12. 12.]
 [24. 24. 24.]
 [24. 24. 24.]] 



In [ ]:
x_inputs = np.random.uniform(-3.0, 3.0, (2, ))
x_inputs

array([ 0.10557304, -2.58176486])

In [ ]:
print(nn.feed_forward(x_inputs))

[ 0.15992971 -0.00331892]


In [ ]:
print(nn.layer_gradients)

[[-0.67245507  0.99629086]
 [ 0.15992971 -0.33189154]
 [ 0.          0.        ]]


In [ ]:
nn.gradient_descent(1.0)

In [ ]:
print(nn.layer_gradients)

[[-0.10754554 -0.33066051]
 [ 0.15992971 -0.33189154]
 [ 1.          1.        ]]


In [ ]:
print(nn.mults)

[[ 0.10557304 -2.58176486  1.        ]
 [-0.00672455  0.99629086  1.        ]]


In [ ]:
a = np.full((3, ), 1)
print(a)

[1 1 1]


In [ ]:
b = np.dot(nn.network[0], a)
print(b)

[ 0.06518128 -0.07288214 -0.46527553]


In [ ]:
c = np.dot(nn.network[0], b)
print(c)

[-0.13911551  0.02873237  0.13100894]
