In [68]:
import numpy as np
import pandas as pd

In [49]:
a = np.array([[1.0, 0.0, 1.0], [2.0, 0.0, 1.0], [3.0, 0.0, 0.0], [4.0, 0.0, 1.0]])
b = np.array([1.0, .0, .0])
c = np.array([2.0, 2.0, 2.0])
print(a, "\n")
print(b, "\n")
# print(b.reshape((3, 1)), "\n")
# print(c.reshape((1, 3)), "\n")
print(np.dot(a, b.reshape(3, 1)), "\n")
# print(a * c, "\n")
# print(a + b, "\n")
# print(a + c, "\n")
#print(np.dot(b.reshape((3, 1)), c.reshape(1, 3)))

[[1. 0. 1.]
 [2. 0. 1.]
 [3. 0. 0.]
 [4. 0. 1.]] 

[1. 0. 0.] 

[[1.]
 [2.]
 [3.]
 [4.]] 



In [104]:
class NeuralNetwork:

  def __init__(self, number_of_neurons, number_of_weights):
    self.size = number_of_neurons
    self.num_neurons = number_of_neurons
    self.hidden_layer = np.random.uniform(-.3, .3, (number_of_neurons, number_of_weights))
    self.gradients = np.zeros((number_of_neurons, number_of_weights))
    self.mults = np.zeros((number_of_weights, 1))
    self.output_layer = np.zeros((number_of_neurons, ))

  def feed_forward(self, input):
    self.mult = input
    sum = np.dot(self.hidden_layer, input)
    exp_sum  = np.exp(sum)
    softmax_sum = exp_sum/np.sum(exp_sum)
    self.output_layer = softmax_sum
    return softmax_sum

  def gradient_descent(self, loss):
    self.gradients += np.dot(loss.reshape((self.size, 1)), self.mult.reshape(1, self.num_neurons))

  def back_propigate(self, a):
    self.hidden_layer -= self.gradients * a
    self.gradients = np.zeros((self.size, self.num_neurons))


In [151]:
N = NeuralNetwork(10, 4)
print(N.hidden_layer)

[[-0.00862918 -0.27745712 -0.09984126  0.09152592]
 [ 0.04446725 -0.22698417  0.04034648 -0.08543457]
 [ 0.28283772  0.09921596  0.29034471  0.01037112]
 [ 0.20507312  0.27016666  0.10741311  0.18259645]
 [-0.28339864  0.12438128  0.10629968  0.13856899]
 [-0.17052037 -0.1220024  -0.15757721  0.12694037]
 [ 0.14742748 -0.01339632 -0.29388577 -0.04564076]
 [-0.15526298  0.29012381  0.03960561  0.17313664]
 [-0.02065136  0.23957959  0.00472844 -0.29265371]
 [-0.15915802 -0.13823434  0.08054194  0.09709964]]


In [167]:
class ProbabilisticGraph:

  def __init__(self):
     self.model = None
     self.graph = dict()
     self.values = list()
     self.dataset = None

  def add(self, vertex_one, vertex_two="None", distance=1):
    if vertex_one not in self.graph.keys():
        self.graph[vertex_one] = []

    self.graph[vertex_one].append(vertex_two)

  def values_to_list(self):
    vals = list()
    for v,k in self.graph.items():
      vals.append(v)
      for j in k:
        vals.append(j)
    self.values = sorted(list(set(vals)))


  def prepare_data(self):
    self.values_to_list()
    size = len(self.values)
    str_to_array = dict()
    for i in range(size):
      arr = np.zeros((size))
      arr[i] = 1
      str_to_array[self.values[i]] = arr

    x_values = list()
    y_values = list()

    for k, v in self.graph.items():
      for i in v:
        x_values.append(str_to_array[k])
        y_values.append(str_to_array[i])

    df = pd.DataFrame()
    df["x_values"] = x_values
    df["y_values"] = y_values

    self.dataset = df

  def fit(self):
    self.prepare_data()
    size = len(self.values)
    self.model = NeuralNetwork(size, size)


    for j in range(5000):
      cost = np.zeros((size, ))
      for i in range(self.dataset.shape[0]):
        pred = self.model.feed_forward(self.dataset.iloc[i, 0])
        y_real = self.dataset.iloc[i, 1]
        loss = pred - y_real
        cost += y_real * np.log(pred)
        self.model.gradient_descent(loss)
      self.model.back_propigate(4e-3)
      cost = -np.sum(cost/size)
      if (cost < 1e-4):
        break

  def predict(self, input):
    index = np.argmax(self.model.feed_forward(input))
    arr = np.zeros((len(self.values), ))
    arr[index] = 1
    return arr

In [168]:
g = ProbabilisticGraph()
g.add("a", "b")
g.add("b", "c")
g.add("c", "d")
g.fit()

1.0711292018437097
1.0688141926556252
1.066503706351718
1.0641977433117076
1.0618963038631688
1.0595993882815589
1.0573069967902473
1.0550191295605469
1.052735786711748
1.0504569683111562
1.0481826743741312
1.0459129048641285
1.043647659692745
1.041386938719765
1.0391307417532096
1.0368790685493905
1.034631918812962
1.0323892921969802
1.030151188302962
1.027917606680946
1.0256885468295578
1.0234640081960782
1.0212439901765102
1.019028492115652
1.016817513307172
1.0146110529936834
1.0124091103668265
1.0102116845673463
1.0080187746851794
1.0058303797595387
1.0036464987790032
1.0014671306816076
0.999292274354936
0.9971219286362181
0.994956092312427
0.9927947641203794
0.9906379427468373
0.9884856268286144
0.9863378149526815
0.9841945056562778
0.9820556974270207
0.97992138870302
0.9777915778729954
0.9756662632763929
0.973545443203506
0.9714291158955981
0.9693172795450284
0.9672099322953764
0.9651070722415737
0.9630086974300327
0.9609148058587818
0.9588253954775992
0.9567404641881515
0.95466

In [169]:
print(g.dataset)

               x_values              y_values
0  [1.0, 0.0, 0.0, 0.0]  [0.0, 1.0, 0.0, 0.0]
1  [0.0, 1.0, 0.0, 0.0]  [0.0, 0.0, 1.0, 0.0]
2  [0.0, 0.0, 1.0, 0.0]  [0.0, 0.0, 0.0, 1.0]


In [172]:
for i in range(g.dataset.shape[0]):
  print(g.dataset.iloc[i, 0], g.predict(g.dataset.iloc[i, 0]))

[1. 0. 0. 0.] [0. 1. 0. 0.]
[0. 1. 0. 0.] [0. 0. 1. 0.]
[0. 0. 1. 0.] [0. 0. 0. 1.]


In [ ]:
print(g.values)

In [ ]:
print(g.dataset)