In [1]:
#Unfinished

In [ ]:
import numpy as np
import time

In [ ]:
def activation(input_array):
  input_activations = np.zeros((input_array.shape[0], ))
  input_activations_gradients = np.zeros((input_array.shape[0], ))
  for i in range(input_array.shape[0]):
    x = input_array[i]
    input_activations[i], input_activations_gradients[i]= (x, 1) if x>0 else (.01 * x, .01)
  return input_activations, input_activations_gradients

In [ ]:
class NeuralNetwork:

  def __init__(self, number_of_layers, number_of_neurons_per_layer):
    self.size = number_of_layers
    self.network = np.empty((number_of_layers, ), dtype=np.ndarray)
    self.gradients = np.empty((number_of_layers, ), dtype=np.ndarray)

    for i in range(self.size):
      #self.network[i] = np.full((self.size, self.size + 1), 1.0)
      self.network[i] = np.random.uniform(-.3, .3, (number_of_neurons_per_layer, number_of_neurons_per_layer + 1))
      self.gradients[i] = np.zeros((self.size, self.size + 1))

    self.activation_gradients = np.zeros((self.size, self.size + 1))
    self.layer_gradients = np.zeros((self.size + 1, self.size))
    self.mults = np.zeros((self.size, self.size + 1))


  def feed_forward(self, x_inputs):
    previous_activations = np.append(x_inputs, 1.0)
    for i in range(self.size):
      self.mults[i] = previous_activations
      temp = np.dot(self.network[i], previous_activations)
      previous_activations, self.activation_gradients[i] = activation(temp)
      if (i + 1 < self.size):
        self.layer_gradients[i] = np.dot(self.network[i + 1], )

    return previous_activations[:previous_activations.shape[0]-1]

  def gradient_descent(self, dE_dOutput):
    output_layer_gradient = np.full((self.layer_gradients.shape[1], ), dE_dOutput)
    self.layer_gradients[self.layer_gradients.shape[0]-1] = output_layer_gradient
    self.layer_gradients = np.flip(np.multiply.accumulate(np.flip(self.layer_gradients)))


  def __repr__(self):
    s = ""
    for i in range(self.network.shape[0]):
      s += f"Layer: {i+1} \n{str(self.network[i])}\n\n"
    return s

In [ ]:
class NeuralNetwork:

  def __init__(self, number_of_layers, number_of_neurons_per_layer):

    self.size = number_of_layers
    self.num_of_neurons = number_of_neurons_per_layer
    self.shape = (number_of_layers, number_of_neurons_per_layer, number_of_neurons_per_layer)
    self.weights = np.random.uniform(-.3, .3, self.shape)
    self.bias = np.full((number_of_layers, number_of_neurons_per_layer), -1.0)
    self.gradient = np.zeros(self.shape)
    self.mults = np.zeros((number_of_layers, number_of_neurons_per_layer, 1))
    self.layer_gradients = np.zeros((number_of_layers, number_of_neurons_per_layer))

  def feed_forward(self, input):
    previous_activations = input
    prev_dot = np.array([])
    for i in range(self.size):
      self.mults[i] = previous_activations.reshape(self.num_of_neurons, 1)
      if (i > 0):
        self.layer_gradients[self.size - i] = prev_dot
      dot_product = np.dot(self.weights[i], previous_activations)
      prev_dot = np.copy(dot_product)
      dot_product += self.bias[i]
      temp, actv_g = activation(dot_product)
      previous_activations = temp
    return previous_activations

  def gradient_descent(self, dE_dOutput):
    self.layer_gradients[0] = np.array([dE_dOutput for _ in range(self.num_of_neurons)])
    g = np.flip(np.multiply.accumulate(self.layer_gradients)).reshape((1, self.size*self.num_of_neurons))
    x = self.mults.reshape((self.size*self.num_of_neurons, 1))
    print(g, "\n")
    print(x, "\n")
    print(np.dot(x, g))
    #print(np.dot(x, g).reshape(self.shape))

  def __repr__(self):
    return f"{self.weights}\n\n {self.bias}"

In [ ]:
NN = NeuralNetwork(2, 2)
print(NN)

[[[ 0.28458866  0.20156266]
  [ 0.26123148 -0.06152426]]

 [[ 0.14765471  0.27795655]
  [-0.09978906 -0.13448345]]]

 [[-1. -1.]
 [-1. -1.]]


In [ ]:
NN.feed_forward(np.ones(2, ))

array([-0.01002983, -0.00998411])

In [ ]:
print(NN.layer_gradients)

[[3.         3.        ]
 [0.48615132 0.19970722]]


In [ ]:
print(NN.mults)

[[[ 1.        ]
  [ 1.        ]]

 [[-0.00513849]
  [-0.00800293]]]


In [ ]:
print(NN.layer_gradients)

[[3.         3.        ]
 [0.48615132 0.19970722]]


In [ ]:
NN.gradient_descent(3.0)

[[0.59912165 1.45845397 3.         3.        ]] 

[[ 1.        ]
 [ 1.        ]
 [-0.00513849]
 [-0.00800293]] 

[[ 0.59912165  1.45845397  3.          3.        ]
 [ 0.59912165  1.45845397  3.          3.        ]
 [-0.00307858 -0.00749425 -0.01541546 -0.01541546]
 [-0.00479473 -0.0116719  -0.02400878 -0.02400878]]


In [ ]:
print(NN)

[[[ 0.28458866  0.20156266]
  [ 0.26123148 -0.06152426]]

 [[ 0.14765471  0.27795655]
  [-0.09978906 -0.13448345]]]

 [[-1. -1.]
 [-1. -1.]]


In [ ]:
start = time.time()
for i in range(10000):
  NN.feed_forward(np.zeros((100, )))
finish = time.time()
print(f"time for 10000 iterations = {finish - start}")

time for 10000 iterations = 7.777102470397949


In [ ]:
26.87026858329773/7.777102470397949

3.455048803275289

In [ ]:
print(nn.weights)

[[[ 0.16392276  0.29188519]
  [-0.06967535  0.11024264]]

 [[ 0.15216147  0.08845144]
  [ 0.15984702 -0.07511981]]]


In [ ]:
print(nn.bias[1])

[-1.]


In [ ]:
arr = np.random.uniform(-.3, .3, (4, ))

In [ ]:
print(arr)
print(np.maximum(arr, arr * .01))
print((1 * (arr > 0)) + (.01 * (arr <= 0)))


[ 0.13656428  0.23466515 -0.15494853 -0.18867521]
[ 0.13656428  0.23466515 -0.00154949 -0.00188675]
[1.   1.   0.01 0.01]


In [ ]:
def act(input_array):
  input_activations = np.zeros((input_array.shape[0], ))
  input_activations_gradients = np.zeros((input_array.shape[0], ))
  for i in range(input_array.shape[0]):
    x = input_array[i]
    input_activations[i], input_activations_gradients[i]= (x, 1) if x>0 else (.01 * x, .01)
  return input_activations, input_activations_gradients

In [ ]:
start = time.time()
for i in range(1000000):
  a = np.maximum(arr, arr * .01)
  b = (1 * (arr > 0)) + (.01 * (arr <= 0))
stop = time.time()
print(a)
print(b)
print(stop - start)

[ 0.13656428  0.23466515 -0.00154949 -0.00188675]
[1.   1.   0.01 0.01]
11.558205127716064


In [ ]:
start = time.time()
for i in range(10000000):
  a, b = act(arr)
stop = time.time()
print(a)
print(b)
print(stop - start)

[ 0.13656428  0.23466515 -0.00154949 -0.00188675]
[1.   1.   0.01 0.01]
37.43606662750244


In [ ]:
start = time.time()
for i in range(10000000):
  a, b = activation(arr)
stop = time.time()
print(a)
print(b)
print(stop - start)

[ 0.13656428  0.23466515 -0.00154949 -0.00188675]
[1.   1.   0.01 0.01]
40.26768207550049


In [ ]:
start = time.time()
for i in range(100000):
  (1 * (arr > 0)) + (.01 * (arr <= 0))
stop = time.time()
print(stop - start)

0.7432358264923096


In [ ]:
a = np.random.uniform(-.3, .3, (4, 2, 2))
b = np.ones((2, ))
c = np.dot(a[0], b)
print(a[0], "\n")
print(b, "\n")
print(c)

[[ 0.06628737 -0.17867107]
 [-0.27926217  0.20872649]] 

[1. 1.] 

[-0.11238369 -0.07053568]


In [ ]:
e = np.ones((2, 1))
print(e, "\n")
print(a[0], "\n")
print(a[0]+e)

[[1.]
 [1.]] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(nn.network.shape)

(4,)


In [ ]:
nn = NeuralNetwork(4, 2)
print(nn)

Layer: 1 
[[-0.25508138  0.11135078  0.03940772]
 [-0.02366981 -0.0851505   0.17403183]]

Layer: 2 
[[ 0.04800862  0.01019903  0.02222631]
 [-0.03369174  0.15615857 -0.17770898]]

Layer: 3 
[[-0.15664641 -0.03205816 -0.29199187]
 [-0.04573103 -0.20276179 -0.0224605 ]]

Layer: 4 
[[-0.17622893  0.08391047 -0.00795108]
 [-0.0896192   0.17306162 -0.01730244]]




In [ ]:
a = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0], [4.0, 4.0, 4.0]])
print(a)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [ ]:
b = np.multiply.accumulate(np.flip(a))
print(np.flip(a), '\n')
print(b, "\n")

[[4. 4. 4.]
 [3. 3. 3.]
 [2. 2. 2.]
 [1. 1. 1.]] 

[[ 4.  4.  4.]
 [12. 12. 12.]
 [24. 24. 24.]
 [24. 24. 24.]] 



In [ ]:
x_inputs = np.random.uniform(-3.0, 3.0, (2, ))
x_inputs

array([ 0.10557304, -2.58176486])

In [ ]:
print(nn.feed_forward(x_inputs))

[ 0.15992971 -0.00331892]


In [ ]:
print(nn.layer_gradients)

[[-0.67245507  0.99629086]
 [ 0.15992971 -0.33189154]
 [ 0.          0.        ]]


In [ ]:
nn.gradient_descent(1.0)

In [ ]:
print(nn.layer_gradients)

[[-0.10754554 -0.33066051]
 [ 0.15992971 -0.33189154]
 [ 1.          1.        ]]


In [ ]:
print(nn.mults)

[[ 0.10557304 -2.58176486  1.        ]
 [-0.00672455  0.99629086  1.        ]]


In [ ]:
a = np.full((3, ), 1)
print(a)

[1 1 1]


In [ ]:
b = np.dot(nn.network[0], a)
print(b)

[ 0.06518128 -0.07288214 -0.46527553]


In [ ]:
c = np.dot(nn.network[0], b)
print(c)

[-0.13911551  0.02873237  0.13100894]
